### ISSUE TITLE
Error When Searching - no function clause matching in DiscoveryApi.Search.DataModelFilterator.data_model_contains_all_facet_values

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/discovery_api#168]
`Request: GET /api/v1/dataset/search?limit=10&query=central%20ohio%20fire%20stations&facets%5Borganization%5D%5B%5D=City%20of%20Columbus&apiAccessible=false
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in DiscoveryApi.Search.DataModelFilterator.data_model_contains_all_facet_values?/2
        (discovery_api) lib/discovery_api/search/data_model_filterator.ex:12: DiscoveryApi.Search.DataModelFilterator.data_model_contains_all_facet_values?(nil, %{organization: ["City of Columbus"]})
        (elixir) lib/enum.ex:2934: Enum.filter_list/2
        (discovery_api) lib/discovery_api_web/controllers/dataset_search_controller.ex:26: DiscoveryApiWeb.DatasetSearchController.search/2
        (discovery_api) lib/discovery_api_web/controllers/dataset_search_controller.ex:3: DiscoveryApiWeb.DatasetSearchController.action/2
        (discovery_api) lib/discovery_api_web/controllers/dataset_search_controller.ex:3: DiscoveryApiWeb.DatasetSearchController.phoenix_controller_pipeline/2
        (discovery_api) lib/discovery_api_web/endpoint.ex:6: DiscoveryApiWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:280: Phoenix.Router.__call__/2
        (discovery_api) lib/discovery_api_web/endpoint.ex:6: DiscoveryApiWeb.Endpoint.plug_builder_call/2`

**Comment by ManApart** [comment]
This bug is due to a dataset's ID existing in Discovery API's cache, but not in Redis. When Discovery API finds a list of dataset ids for datasets that match a query, and one or more datasets no longer exist in redis, this error is thrown.
We resolved this in prod by rebuilding the cache (rolling the pod) and updated the code in discovery API to not break if the cache gets out of sync again.

**Comment by smillardHNTB** [comment]
This happens due to the model existing in the ETS lookup table but not in redis.   
As a temporary solution you can reindex the deleted dataset which will remove all entries from the ETS table.
Before:
`:ets.lookup(DiscoveryApi.Search.Storage, "word_that_exists_in_description")` should return a list containing the word and a dataset id
Then run:
`DiscoveryApi.Search.Storage.index("<dataset_id>)`

Then run the above lookup again and it should return an empty list

**Comment by smillardHNTB** [comment]
Still happening on discovery_api:0.13.8
